### ISSUE TITLE
onSuccess and onError callbacks

### ISSUE THREAD

**Issue by aschmi** [cesarandreu/angular-server-form#1]
Thank you very much for sharing, Cesar!

I'm having the problem that I want to register for the onSuccess callback but my closeDialog() function gets called several times when I open the form and when I'm submitting it. However, it doesn't get called after submit.

My form looks like this:

`<form accept-charset="UTF-8" action="/brands" class="simple_form new_hard_brand ng-isolate-scope ng-pristine ng-valid" id="new_brand" method="post" name="brand" novalidate="novalidate" on-success="closeDialog()" server-form="true" url="/brands.json">`

closeDialog() is a very simple function in my controller.

Am I missing something here?

**Comment by cesarandreu** [comment]
The `on-success` callback expects a scope function and it gets called as the success callback of [HttpPromise](https://docs.angularjs.org/api/ng/service/$http). 

It's just like if you were doing `httpPromise.then(onSuccess, onError)`.

To fix it just do `on-success="closeDialog"`.

I should update the documentation to be clearer and provide an example.

Thanks for letting me know, and let me know if it works!

**Comment by aschmi** [comment]
Works like a charm, thank you! :+1: 

Was easier than I thought ;)

**Comment by cesarandreu** [comment]
Glad to see that it worked. :)
